/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124254-g397c7c7524-20260429"
#endif /* AVUTIL_FFVERSION_H */
